# TODO: Should not use apt but package
- name: Install packages
  ansible.builtin.apt:
    name:
      - acl  # needed for, e.g., using become_user to change from an unprivileged user to another unprivileged user
      - python-setuptools
      - zsh
    state: present
    update_cache: true

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Make sure we have a 'docker' group
  ansible.builtin.group:
    name: docker
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# - name: Set up Wireguard network
#   ansible.builtin.include_role:
#     name: githubixx.ansible_role_wireguard
#     apply:
#       tags: wireguard
#   tags: wireguard

- name: Install Prometheus Node Exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      tags: node-exporter
  vars:
    node_exporter_web_listen_address: "0.0.0.0:{{ server_node_exporter_port }}"
  tags: node-exporter

- name: Put private network hosts into /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }} # ansible$'
    line: "{{ hostvars[item].private_network_ip }} {{ item }} # ansible"
    state: present
  when: hostvars[item].private_network_ip is defined
  with_items: "{{ groups.all }}"
  tags: hosts

- name: Set up firewall
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags: firewall
  tags: firewall

# Changes to sshd config have been set up by hardening role in dependencies
- name: Reload sshd config
  ansible.builtin.service:
    name: sshd
    state: reloaded
