- name: Run os_hardening role
  ansible.builtin.include_role:
    name: devsec.hardening.os_hardening
  vars:
    os_auth_pw_min_age: 0
    os_auth_pw_max_age: 99999
    os_auth_retries: 10
    os_auditd_enabled: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding for docker, see https://galaxy.ansible.com/dev-sec/os-hardening
      net.ipv4.ip_forward: 1
      # Enable IPv6 because otherwise there would be an error trying to bring up eth0 on Hetzner servers, which define
      # an IPv6 address in /etc/network/interfaces.d/50-cloud-init. (Alternatively, one could disable cloud-init's
      # network configuration as suggested in that file.)
      net.ipv6.conf.all.disable_ipv6: 0

- name: Run ssh_hardening role
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening
  vars:
    sftp_enabled: true
    ssh_allow_tcp_forwarding: "yes"
    ssh_max_auth_retries: 5
    ssh_print_motd: true
    ssh_print_pam_motd: true

# TODO: Should not use apt but package
- name: Install packages
  ansible.builtin.apt:
    name:
      - acl  # needed for, e.g., using become_user to change from an unprivileged user to another unprivileged user
      - python-setuptools
      - zsh
    state: present
    update_cache: true

- name: Install mailx for sending emails concerning unattended updates
  ansible.builtin.package:
    name: bsd-mailx
  when: unattended_mail

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Make sure we have a 'docker' group
  ansible.builtin.group:
    name: docker
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# - name: Set up Wireguard network
#   ansible.builtin.include_role:
#     name: githubixx.ansible_role_wireguard
#     apply:
#       tags: wireguard
#   tags: wireguard

- name: Install Prometheus Node Exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      tags: node-exporter
  vars:
    node_exporter_web_listen_address: "0.0.0.0:{{ server_node_exporter_port }}"
  tags: node-exporter

- name: Put private network hosts into /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }} # ansible$'
    line: "{{ hostvars[item].private_network_ip }} {{ item }} # ansible"
    state: present
  when: hostvars[item].private_network_ip is defined
  with_items: "{{ groups.all }}"
  tags: hosts

- name: Set up firewall
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags: firewall
  tags: firewall
